// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Prisma does not support a TypeScript config file out of the box.
// Configuration should be done in schema.prisma and .env files.
// If you need to access the DATABASE_URL, use process.env.DATABASE_URL as needed.
